askdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),

    path('<int:post_pk>/comments/new/', views.comment_new, name='comment_new'),
    path('<int:post_pk>/comments/<int:pk>/edit/', views.comment_edit, name='comment_edit'),
    path('<int:post_pk>/comments/<int:pk>/delete/', views.comment_delete, name='comment_delete'),
]

blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()
    photo = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

blog/views.py
from django.shortcuts import get_object_or_404, render, resolve_url
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Post, Comment


index = ListView.as_view(model=Post, template_name='blog/index.html')

post_new = CreateView.as_view(model=Post, fields='__all__')

post_detail = DetailView.as_view(model=Post)

post_edit = UpdateView.as_view(model=Post, fields='__all__')

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

post_delete = PostDeleteView.as_view()


class CommentCreateView(CreateView):
    model = Comment
    fields=['message']

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk=self.kwargs['post_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return resolve_url(self.object.post)

comment_new = CommentCreateView.as_view()


class CommentUpdateView(UpdateView):
    model = Comment
    fields=['message']

    def get_success_url(self):
        return resolve_url(self.object.post)

comment_edit = CommentUpdateView.as_view()


class CommentDeleteView(DeleteView):
    model = Comment

    def get_success_url(self):
        return resolve_url(self.object.post)

comment_delete = CommentDeleteView.as_view()

blog/templates/blog/comment_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>
    정말 삭제하시겠습니까? 후회없죠?
    </p>
    <input type="submit" value="삭제하세요!" />
</form>

blog/templates/blog/comment_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit"/>
</form>

blog/templates/blog/index.html
<table>
    <tbody>
        {% for post in post_list %}
            <tr>
                <td>
                    <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                    </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<hr/>

<a href="{% url "blog:post_new" %}">새 글쓰기</a>

blog/templates/blog/post_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>
        정말 삭제하시겠습니까? 후회없죠?
    </p>
    <input type="submit" value="삭제하세요!"/>
</form>

blog/templates/blog/post_detail.html
<h1>{{ post.title}}</h1>

{{ post.content|linebreaks }}

<hr/>

<ul>
{% for comment in post.comment_set.all %}
    <li>
        {{ comment.message }}
        &dash;
        <a href="{% url "blog:comment_edit" post.pk comment.pk %}">
            <small>{{ comment.updated_at }}</small>
        </a>
        <a href="{% url "blog:comment_delete" post.pk comment.pk %}">
            <small>삭제</small>
        </a>
    </li>
{% endfor %}
</ul>

<hr/>

<a href="{% url 'blog:index' %}">목록</a>
<a href="{% url 'blog:post_edit' post.pk %}">수정</a>
<a href="{% url 'blog:post_delete' post.pk %}">삭제</a>

<a href="{% url 'blog:comment_new' post.pk %}">댓글쓰기</a>

blog/templates/blog/post_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit"/>
</form>